In [ ]:
#!pip install pyfixest

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import scipy
import statsmodels

In [ ]:
df = pd.read_csv("/content/Survey on Art Appreciation Across Genres_March 6, 2024_14.46.csv")
df

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q42_1,Q43_1,Q44_1,Q45_1,Q46_1,Q47_1,Q48_1,FL_6_DO,"Now,wearegoingtoshowyousomeAIgeneratedartwork._DO","Now,wearegoingtoshowyousomeartwork._DO"
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,"On a scale of 0 to 100, how much do you like t...","On a scale of 0 to 100, how much do you like t...","On a scale of 0 to 100, how much do you like t...","On a scale of 0 to 100, how much do you like t...","On a scale of 0 to 100, how much do you like t...","On a scale of 0 to 100, how much do you like t...","On a scale of 0 to 100, how much do you like t...",FL_6 - Block Randomizer - Display Order,"Now, we are going to show you some AI generate...","Now, we are going to show you some artwork. - ..."
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID68_1""}","{""ImportId"":""QID69_1""}","{""ImportId"":""QID70_1""}","{""ImportId"":""QID71_1""}","{""ImportId"":""QID72_1""}","{""ImportId"":""QID73_1""}","{""ImportId"":""QID74_1""}","{""ImportId"":""FL_6_DO""}","{""ImportId"":""BL_87fwM5P0vrKbtRA_DO""}","{""ImportId"":""BL_elMwmDZKkA2tY6W_DO""}"
2,2024-02-27 15:41:48,2024-02-27 15:42:30,IP Address,128.197.29.239,100,42,True,2024-02-27 15:42:31,R_3xAe7rrjjOl3cvI,NaN,...,NaN,NaN,7,88,NaN,97,NaN,FL_18,NaN,Q45|Q36|Q32|Q47|Q40|Q34|Q29|Q44|Q37|Q33
3,2024-02-27 16:32:59,2024-02-27 16:34:44,IP Address,128.197.29.243,100,105,True,2024-02-27 16:34:44,R_1uyY8diTp1PSRsw,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_14,Q19|Q8|Q26|Q6|Q13|Q21|Q17|Q18|Q22|Q14,NaN
4,2024-02-27 18:20:24,2024-02-27 18:21:08,IP Address,12.74.53.20,100,44,True,2024-02-27 18:21:09,R_7Osf8LBzuHb7Njb,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_14,Q9|Q10|Q6|Q16|Q12|Q18|QID78|Q21|Q13|Q19,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,2024-02-28 03:17:40,2024-02-28 03:18:01,IP Address,117.102.155.245,57,20,False,2024-03-06 03:18:01,R_4jjMsY2lJHDNDrj,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_14,Q25|Q18|Q23|Q12|Q20|Q22|Q9|Q5|Q26|Q16,NaN
179,2024-02-28 07:22:24,2024-02-28 07:22:36,IP Address,128.197.29.249,55,11,False,2024-03-06 07:23:08,R_5LH9WiuXdNPkMjW,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_18,NaN,NaN
180,2024-02-28 10:02:17,2024-02-28 10:02:45,IP Address,128.197.29.240,57,28,False,2024-03-06 10:08:52,R_6Mi6hT5rdvgips5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_14,Q11|Q5|Q19|Q10|Q9|Q23|Q22|Q6|Q17|Q24,NaN
181,2024-02-28 10:46:46,2024-02-28 10:47:20,IP Address,204.8.153.51,57,34,False,2024-03-06 10:47:24,R_3p2TYISUqsWqibH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_18,NaN,Q32|Q48|Q38|Q37|Q36|Q43|Q29|Q46|Q42|Q47
182,2024-02-28 11:56:35,2024-02-28 11:57:00,IP Address,71.233.185.162,57,24,False,2024-03-06 11:57:05,R_2HbgGH7Kq39ExHz,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_14,Q9|Q25|Q12|Q18|Q7|Q20|Q19|Q8|Q10|Q14,NaN

In [ ]:
df = df.drop(df.index[0:2])
df.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q42_1,Q43_1,Q44_1,Q45_1,Q46_1,Q47_1,Q48_1,FL_6_DO,"Now,wearegoingtoshowyousomeAIgeneratedartwork._DO","Now,wearegoingtoshowyousomeartwork._DO"
2,2024-02-27 15:41:48,2024-02-27 15:42:30,IP Address,128.197.29.239,100,42,True,2024-02-27 15:42:31,R_3xAe7rrjjOl3cvI,NaN,...,NaN,NaN,7,88,NaN,97,NaN,FL_18,NaN,Q45|Q36|Q32|Q47|Q40|Q34|Q29|Q44|Q37|Q33
3,2024-02-27 16:32:59,2024-02-27 16:34:44,IP Address,128.197.29.243,100,105,True,2024-02-27 16:34:44,R_1uyY8diTp1PSRsw,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_14,Q19|Q8|Q26|Q6|Q13|Q21|Q17|Q18|Q22|Q14,NaN
4,2024-02-27 18:20:24,2024-02-27 18:21:08,IP Address,12.74.53.20,100,44,True,2024-02-27 18:21:09,R_7Osf8LBzuHb7Njb,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_14,Q9|Q10|Q6|Q16|Q12|Q18|QID78|Q21|Q13|Q19,NaN
5,2024-02-27 18:20:27,2024-02-27 18:21:21,IP Address,128.197.29.246,100,54,True,2024-02-27 18:21:21,R_3NVSnApOBSug4Wa,NaN,...,59,NaN,NaN,NaN,20,11,15,FL_18,NaN,Q29|Q42|Q46|Q39|Q40|Q36|Q32|Q35|Q47|Q48
6,2024-02-27 18:20:23,2024-02-27 18:21:25,IP Address,128.197.29.243,100,62,True,2024-02-27 18:21:26,R_5NLpdRxCZbqhJda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FL_14,Q17|Q6|Q16|Q15|QID78|Q24|Q19|Q9|Q23|Q18,NaN

In [ ]:
df.columns

Index(['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'ResponseId',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage', 'Q1', 'Q2', 'Q3', 'Q4',
       'Q4_13_TEXT', 'Q5_1', 'Q6_1', 'Q7_1', 'Q8_1', 'Q9_1', 'Q10_1', 'Q11_1',
       'Q12_1', 'Q13_1', 'Q14_1', 'Q15_1', 'Q16_1', 'Q17_1', 'Q18_1', 'Q19_1',
       'Q20_1', 'Q21_1', 'Q22_1', 'Q23_1', 'Q24_1', 'Q25_1', 'Q26_1', 'Q27_1',
       'Q28_1', 'Q29_1', 'Q30_1', 'Q31_1', 'Q32_1', 'Q33_1', 'Q34_1', 'Q35_1',
       'Q36_1', 'Q37_1', 'Q38_1', 'Q39_1', 'Q40_1', 'Q41_1', 'Q42_1', 'Q43_1',
       'Q44_1', 'Q45_1', 'Q46_1', 'Q47_1', 'Q48_1', 'FL_6_DO',
       'Now,wearegoingtoshowyousomeAIgeneratedartwork._DO',
       'Now,wearegoingtoshowyousomeartwork._DO'],
      dtype='object')

In [ ]:
df.drop(["Status", "IPAddress", "ResponseId", "RecipientLastName",
         "RecipientFirstName", "RecipientEmail", "ExternalReference",
         "LocationLatitude", "LocationLongitude", "DistributionChannel",
         "UserLanguage", "RecordedDate", "Q4_13_TEXT", "FL_6_DO", "Progress"], axis=1, inplace=True)

In [ ]:
df.columns

Index(['StartDate', 'EndDate', 'Duration (in seconds)', 'Finished', 'Q1', 'Q2',
       'Q3', 'Q4', 'Q5_1', 'Q6_1', 'Q7_1', 'Q8_1', 'Q9_1', 'Q10_1', 'Q11_1',
       'Q12_1', 'Q13_1', 'Q14_1', 'Q15_1', 'Q16_1', 'Q17_1', 'Q18_1', 'Q19_1',
       'Q20_1', 'Q21_1', 'Q22_1', 'Q23_1', 'Q24_1', 'Q25_1', 'Q26_1', 'Q27_1',
       'Q28_1', 'Q29_1', 'Q30_1', 'Q31_1', 'Q32_1', 'Q33_1', 'Q34_1', 'Q35_1',
       'Q36_1', 'Q37_1', 'Q38_1', 'Q39_1', 'Q40_1', 'Q41_1', 'Q42_1', 'Q43_1',
       'Q44_1', 'Q45_1', 'Q46_1', 'Q47_1', 'Q48_1',
       'Now,wearegoingtoshowyousomeAIgeneratedartwork._DO',
       'Now,wearegoingtoshowyousomeartwork._DO'],
      dtype='object')

In [ ]:
df.head()

,StartDate,EndDate,Duration (in seconds),Finished,Q1,Q2,Q3,Q4,Q5_1,Q6_1,...,Q41_1,Q42_1,Q43_1,Q44_1,Q45_1,Q46_1,Q47_1,Q48_1,"Now,wearegoingtoshowyousomeAIgeneratedartwork._DO","Now,wearegoingtoshowyousomeartwork._DO"
2,2024-02-27 15:41:48,2024-02-27 15:42:30,42,True,18 - 24,Male,Yes,Questrom School of Business,NaN,NaN,...,NaN,NaN,NaN,7,88,NaN,97,NaN,NaN,Q45|Q36|Q32|Q47|Q40|Q34|Q29|Q44|Q37|Q33
3,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,Yes,Questrom School of Business,NaN,77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q19|Q8|Q26|Q6|Q13|Q21|Q17|Q18|Q22|Q14,NaN
4,2024-02-27 18:20:24,2024-02-27 18:21:08,44,True,18 - 24,Male,Yes,Questrom School of Business,NaN,58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q9|Q10|Q6|Q16|Q12|Q18|QID78|Q21|Q13|Q19,NaN
5,2024-02-27 18:20:27,2024-02-27 18:21:21,54,True,18 - 24,Female,Yes,Questrom School of Business,NaN,NaN,...,NaN,59,NaN,NaN,NaN,20,11,15,NaN,Q29|Q42|Q46|Q39|Q40|Q36|Q32|Q35|Q47|Q48
6,2024-02-27 18:20:23,2024-02-27 18:21:25,62,True,25 - 34,Male,Yes,Questrom School of Business,NaN,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q17|Q6|Q16|Q15|QID78|Q24|Q19|Q9|Q23|Q18,NaN

In [ ]:
df = df[df["Finished"] == "True"]

In [ ]:
df.columns = ['StartDate', 'EndDate', 'Duration (in seconds)', 'Finished',
       'Age', 'Gender', 'Attend_BU', 'BU_School', 'Q5_1', 'Q6_1', 'Q7_1', 'Q8_1',
       'Q9_1', 'Q10_1', 'Q11_1', 'Q12_1', 'Q13_1', 'Q14_1', 'Q15_1', 'Q16_1',
       'Q17_1', 'Q18_1', 'Q19_1', 'Q20_1', 'Q21_1', 'Q22_1', 'Q23_1', 'Q24_1',
       'Q25_1', 'Q26_1', 'Q27_1', 'Q28_1', 'Q29_1', 'Q30_1', 'Q31_1', 'Q32_1',
       'Q33_1', 'Q34_1', 'Q35_1', 'Q36_1', 'Q37_1', 'Q38_1', 'Q39_1', 'Q40_1',
       'Q41_1', 'Q42_1', 'Q43_1', 'Q44_1', 'Q45_1', 'Q46_1', 'Q47_1', 'Q48_1', 'Treatment', 'Control']

In [ ]:
df_treatment = df[df["Treatment"].notna()]

In [ ]:
df_control = df[df["Control"].notna()]

In [ ]:
df_control = df_control.drop(['Q5_1', 'Q6_1', 'Q7_1', 'Q8_1',
       'Q9_1', 'Q10_1', 'Q11_1', 'Q12_1', 'Q13_1', 'Q14_1', 'Q15_1', 'Q16_1',
       'Q17_1', 'Q18_1', 'Q19_1', 'Q20_1', 'Q21_1', 'Q22_1', 'Q23_1', 'Q24_1',
       'Q25_1', "Q26_1"], axis = 1)

In [ ]:
df_treatment = df_treatment.drop(['Q27_1', 'Q28_1', 'Q29_1', 'Q30_1', 'Q31_1', 'Q32_1',
       'Q33_1', 'Q34_1', 'Q35_1', 'Q36_1', 'Q37_1', 'Q38_1', 'Q39_1', 'Q40_1',
       'Q41_1', 'Q42_1', 'Q43_1', 'Q44_1', 'Q45_1', 'Q46_1', 'Q47_1', 'Q48_1'], axis = 1)

In [ ]:
df_control.columns = df_treatment.columns

In [ ]:
(df_control.shape, df_treatment.shape)

((84, 32), (81, 32))

In [ ]:
df_cleaned = pd.concat([df_treatment, df_control], ignore_index=True)

In [ ]:
df_cleaned["Any_Treatment"] = df_cleaned["Treatment"].apply(lambda x: 0 if pd.isna(x) else 1)
df_cleaned.drop(["Treatment", "Control"], axis = 1, inplace = True)

In [ ]:
df_cleaned.columns = [
    "StartDate", "EndDate", "Duration (in seconds)", "Finished", "Age",
    "Gender", "Attend_BU", "BU_School",
    "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "Any_Treatment"]

In [ ]:
columns_to_sum =  ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22"]

count_per_row = df_cleaned[columns_to_sum].count(axis=1)

rows_to_drop = count_per_row[count_per_row <= 9].index

df_cleaned.drop(index=rows_to_drop, inplace=True)

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 147 entries, 0 to 164
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   StartDate              147 non-null    object
 1   EndDate                147 non-null    object
 2   Duration (in seconds)  147 non-null    object
 3   Finished               147 non-null    object
 4   Age                    147 non-null    object
 5   Gender                 147 non-null    object
 6   Attend_BU              147 non-null    object
 7   BU_School              57 non-null     object
 8   1                      65 non-null     object
 9   2                      66 non-null     object
 10  3                      65 non-null     object
 11  4                      60 non-null     object
 12  5                      58 non-null     object
 13  6                      67 non-null     object
 14  7                      57 non-null     object
 15  8                      68 non-null     object
 16  9                      65 non-null     object
 17  10                     71 non-null     object
 18  11                     64 non-null     object
 19  12                     65 non-null     object
 20  13                     70 non-null     object
 21  14                     71 non-null     object
 22  15                     65 non-null     object
 23  16                     69 non-null     object
 24  17                     69 non-null     object
 25  18                     60 non-null     object
 26  19                     73 non-null     object
 27  20                     75 non-null     object
 28  21                     76 non-null     object
 29  22                     71 non-null     object
 30  Any_Treatment          147 non-null    int64
dtypes: int64(1), object(30)
memory usage: 36.8+ KB

In [ ]:
df_cleaned[["StartDate", "EndDate"]] = df_cleaned[["StartDate", "EndDate"]].apply(pd.to_datetime)

In [ ]:
df_cleaned["StartHour"] = df_cleaned["StartDate"].dt.hour
df_cleaned["EndHour"] = df_cleaned["EndDate"].dt.hour

In [ ]:
import plotly.graph_objs as go

mean_score_by_start_hour = df_cleaned.groupby("StartHour")["Mean_Score"].mean()

fig = go.Figure()

fig.add_trace(go.Scatter(x=mean_score_by_start_hour.index,
                         y=mean_score_by_start_hour.values,
                         mode='lines+markers',
                         marker=dict(color='blue'),
                         line=dict(width=2),
                         name='Mean Score'))

fig.update_layout(title='Mean Score vs Start Hour',
                  xaxis_title='Start Hour',
                  yaxis_title='Mean Score',
                  xaxis=dict(tickvals=list(range(24))),
                  yaxis=dict(gridcolor='lightgray'),
                  plot_bgcolor='rgba(0,0,0,0)')

fig.show()

In [ ]:
import plotly.graph_objs as go

count_by_start_hour = df_cleaned['StartHour'].value_counts().sort_index()

fig = go.Figure()

fig.add_trace(go.Scatter(x=count_by_start_hour.index,
                         y=count_by_start_hour.values,
                         mode='lines+markers',
                         marker=dict(color='blue'),
                         line=dict(width=2),
                         name='Count'))

fig.update_layout(title='Count of Observations vs Start Hour',
                  xaxis_title='Start Hour',
                  yaxis_title='Count',
                  xaxis=dict(tickvals=list(range(24))),
                  yaxis=dict(gridcolor='lightgray'),
                  plot_bgcolor='rgba(0,0,0,0)')

fig.show()

In [ ]:
import plotly.graph_objs as go

mean_score_by_start_hour = df_cleaned.groupby("StartHour")["Mean_Score"].mean()
count_by_start_hour = df_cleaned['StartHour'].value_counts().sort_index()

fig = go.Figure()

fig.add_trace(go.Scatter(x=mean_score_by_start_hour.index,
                         y=mean_score_by_start_hour.values,
                         mode='lines+markers',
                         marker=dict(color='blue'),
                         line=dict(width=2),
                         name='Mean Score'))

fig.add_trace(go.Scatter(x=count_by_start_hour.index,
                         y=count_by_start_hour.values,
                         mode='lines+markers',
                         marker=dict(color='red'),
                         line=dict(width=2),
                         name='Count'))

fig.update_layout(title='Mean Score and Count of Observations vs Start Hour',
                  xaxis_title='Start Hour',
                  yaxis_title='Value',
                  xaxis=dict(tickvals=list(range(24))),
                  yaxis=dict(gridcolor='lightgray'),
                  plot_bgcolor='rgba(0,0,0,0)',
                  width=800,
                  height=500)

fig.show()

In [ ]:
column_to_int = ["Duration (in seconds)"]
df_cleaned[column_to_int] = df_cleaned[column_to_int].apply(pd.to_numeric, errors='coerce')

In [ ]:
df_cleaned["Finished"] = df_cleaned["Finished"].astype(bool)

In [ ]:
mapping_bu = {"Yes": True, "No": False}

df_cleaned["Attend_BU"] = df_cleaned["Attend_BU"].map(mapping_bu)

In [ ]:
df_cleaned["Any_Treatment"].value_counts()

0    76
1    71
Name: Any_Treatment, dtype: int64

In [ ]:
df_cleaned[columns_to_sum] = df_cleaned[columns_to_sum].apply(pd.to_numeric, errors='coerce')

In [ ]:
df_cleaned[columns_to_sum].sum(axis=1).sort_values()

76       67.0
28      192.0
21      230.0
14      261.0
27      319.0
        ...
36      933.0
74      969.0
152    1000.0
41     1000.0
120    1000.0
Length: 147, dtype: float64

In [ ]:
row_sums = df_cleaned[columns_to_sum].sum(axis=1)

rows_to_drop_2 = row_sums[row_sums == 1000].index

df_cleaned.drop(index=rows_to_drop_2, inplace=True)

df_cleaned.reset_index().drop("index", axis = 1, inplace = True)

In [ ]:
max_end_date = df_cleaned["EndDate"].max()
min_start_date = df_cleaned["StartDate"].min()
experiment_timeframe = max_end_date - min_start_date

print("First Submission:", min_start_date)
print("Last Submission:", max_end_date)
print("Experiment Timeframe:", experiment_timeframe)

First Submission: 2024-02-27 15:41:48
Last Submission: 2024-02-29 05:00:14
Experiment Timeframe: 1 days 13:18:26

In [ ]:
df_cleaned["Mean_Score"] = df_cleaned[columns_to_sum].sum(axis=1)/ 10
df_cleaned

,StartDate,EndDate,Duration (in seconds),Finished,Age,Gender,Attend_BU,BU_School,1,2,...,15,16,17,18,19,20,21,22,Any_Treatment,Mean_Score
0,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,NaN,77.0,...,71.0,NaN,78.0,64.0,NaN,NaN,NaN,30.0,1,71.9
3,2024-02-27 18:28:51,2024-02-27 18:30:36,104,True,18 - 24,Male,True,Questrom School of Business,NaN,NaN,...,NaN,NaN,NaN,0.0,62.0,60.0,NaN,87.0,1,57.5
5,2024-02-27 18:29:36,2024-02-27 18:30:53,76,True,18 - 24,Male,True,Questrom School of Business,37.0,100.0,...,97.0,57.0,68.0,51.0,NaN,NaN,NaN,76.0,1,72.4
7,2024-02-27 18:30:48,2024-02-27 18:32:06,78,True,18 - 24,Female,True,Questrom School of Business,100.0,100.0,...,100.0,NaN,NaN,NaN,NaN,NaN,40.0,NaN,1,70.9
11,2024-02-27 18:36:16,2024-02-27 18:41:37,321,True,25 - 34,Male,True,Questrom School of Business,NaN,86.0,...,NaN,40.0,NaN,19.0,NaN,77.0,51.0,NaN,1,68.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,2024-02-28 16:49:23,2024-02-28 16:50:25,61,True,25 - 34,Female,False,NaN,NaN,NaN,...,NaN,50.0,NaN,41.0,82.0,63.0,23.0,NaN,0,57.6
161,2024-02-28 20:37:47,2024-02-28 20:39:08,80,True,18 - 24,Female,True,Questrom School of Business,53.0,11.0,...,NaN,74.0,NaN,NaN,NaN,NaN,50.0,NaN,0,54.3
162,2024-02-28 20:57:09,2024-02-28 20:59:26,137,True,25 - 34,Male,False,NaN,NaN,70.0,...,80.0,70.0,NaN,20.0,85.0,71.0,NaN,80.0,0,63.1
163,2024-02-29 00:12:08,2024-02-29 00:14:13,124,True,18 - 24,Male,False,NaN,NaN,NaN,...,NaN,100.0,95.0,NaN,NaN,100.0,90.0,NaN,0,91.5
164,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,62.0,NaN,...,NaN,43.0,NaN,36.0,NaN,NaN,NaN,63.0,0,63.6

In [ ]:
df_cleaned["User_ID"] = np.arange(len(df_cleaned))+1

In [ ]:
df_cleaned_categorical = df_cleaned[["StartDate", "EndDate", "Duration (in seconds)", "Finished", "Age", "Gender", "Attend_BU", "BU_School", "User_ID", "Any_Treatment", "Mean_Score"]]

In [ ]:
import numpy as np

non_null_values_list = []

for index, row in df_cleaned[columns_to_sum].iterrows():
    non_null_values = row.dropna().values
    non_null_values_list.append(non_null_values)

non_null_values_array = np.array(non_null_values_list)
non_null_values_array = non_null_values_array

In [ ]:
df_cleaned_categorical_repeated = df_cleaned_categorical.loc[df_cleaned_categorical.index.repeat(10)].reset_index(drop=True)

In [ ]:
non_null_values_flat = non_null_values_array.flatten()

df_cleaned_categorical_repeated["Score"] = non_null_values_flat

In [ ]:
df_cleaned_categorical_repeated

,StartDate,EndDate,Duration (in seconds),Finished,Age,Gender,Attend_BU,BU_School,User_ID,Any_Treatment,Mean_Score,Score
0,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,77.0
1,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,87.0
2,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,85.0
3,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,99.0
4,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,89.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1435,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,100.0
1436,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,100.0
1437,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,43.0
1438,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,36.0
1439,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,63.0

In [ ]:
import pandas as pd

column_name_list = []

for index, row in df_cleaned[columns_to_sum].iterrows():
    for column in columns_to_sum:
        value = row[column]
        if not pd.isna(value):
            column_name_list.append(column)

len(column_name_list)

1440

In [ ]:
df_cleaned_categorical_repeated["Image_ID"] = column_name_list

In [ ]:
df_cleaned_categorical_repeated

,StartDate,EndDate,Duration (in seconds),Finished,Age,Gender,Attend_BU,BU_School,User_ID,Any_Treatment,Mean_Score,Score,Image_ID
0,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,77.0,2
1,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,87.0,4
2,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,85.0,9
3,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,99.0,10
4,2024-02-27 16:32:59,2024-02-27 16:34:44,105,True,18 - 24,Male,True,Questrom School of Business,1,1,71.9,89.0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,100.0,12
1436,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,100.0,14
1437,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,43.0,16
1438,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,36.0,18
1439,2024-02-29 04:58:33,2024-02-29 05:00:14,100,True,25 - 34,Male,False,NaN,144,0,63.6,63.0,22

In [ ]:
df_cleaned_categorical_repeated["Age"].value_counts()/10

18 - 24              72.0
25 - 34              59.0
45 - 54               5.0
35 - 44               4.0
Under 18              2.0
55 and older          1.0
Prefer not to say     1.0
Name: Age, dtype: float64

In [ ]:
from pyfixest.estimation import feols
from pyfixest.summarize import etable

model_score = feols(f"Score ~ Any_Treatment + Age + Gender + Attend_BU + Image_ID", data=df_cleaned_categorical_repeated).vcov("hetero")

model_score_simple = feols(f"Score ~ Any_Treatment + Age + Gender + Image_ID", data=df_cleaned_categorical_repeated).vcov("hetero")

model_score_fe = feols(f"Score ~ Any_Treatment + Age + Gender + Attend_BU | Image_ID", data=df_cleaned_categorical_repeated).vcov("hetero")

etable([model_score, model_score_simple, model_score_fe])

                                                   est1                est2                est3
-----------------------------------  ------------------  ------------------  ------------------
depvar                                            Score               Score               Score
-----------------------------------------------------------------------------------------------
Intercept                             67.487*** (3.987)   65.167*** (3.969)
Any_Treatment                            -2.468 (1.311)      -2.032 (1.298)      -2.468 (1.301)
Age[T.25 - 34]                            0.365 (1.379)       1.386 (1.367)       0.365 (1.369)
Age[T.35 - 44]                            5.616 (3.371)      6.847* (3.450)       5.616 (3.345)
Age[T.45 - 54]                       -14.329*** (2.971)  -12.819*** (2.953)  -14.329*** (2.949)
Age[T.55 and older]                     9.591** (3.195)   11.777*** (3.141)     9.591** (3.171)
Age[T.Prefer not to say]                 -1.888 (6.711)      -4.312 (6.642)      -1.888 (6.659)
Age[T.Under 18]                           2.318 (4.402)       4.428 (4.367)       2.318 (4.368)
Gender[T.Male]                          4.216** (1.295)     4.269** (1.300)     4.216** (1.285)
Gender[T.Non-binary / third gender]  -36.302*** (5.297)  -34.425*** (5.373)  -36.302*** (5.256)
Attend_BU                              -4.515** (1.378)                       -4.515*** (1.367)
Image_ID[T.10]                           -9.225 (4.810)     -9.629* (4.822)
Image_ID[T.11]                            6.204 (4.554)       5.657 (4.570)
Image_ID[T.12]                         13.259** (4.657)    12.722** (4.678)
Image_ID[T.13]                           9.862* (4.472)      9.391* (4.521)
Image_ID[T.14]                         -11.485* (4.996)    -11.564* (5.010)
Image_ID[T.15]                            5.016 (4.868)       4.697 (4.865)
Image_ID[T.16]                           -0.854 (4.590)      -0.900 (4.623)
Image_ID[T.17]                            1.853 (4.787)       1.745 (4.833)
Image_ID[T.18]                       -24.181*** (4.908)  -24.381*** (4.955)
Image_ID[T.19]                            8.707 (4.468)       8.374 (4.478)
Image_ID[T.2]                             2.444 (4.947)       2.264 (4.966)
Image_ID[T.20]                            2.185 (4.942)       1.781 (4.928)
Image_ID[T.21]                         -10.455* (4.643)    -10.537* (4.675)
Image_ID[T.22]                            3.017 (4.954)       2.843 (4.963)
Image_ID[T.3]                             6.561 (4.993)       6.296 (5.034)
Image_ID[T.4]                             2.483 (4.759)       2.341 (4.766)
Image_ID[T.5]                            -5.295 (4.840)      -5.584 (4.875)
Image_ID[T.6]                           -9.810* (4.780)    -10.222* (4.791)
Image_ID[T.7]                             3.882 (4.931)       3.513 (4.996)
Image_ID[T.8]                            -8.981 (4.742)      -9.107 (4.775)
Image_ID[T.9]                             3.264 (4.937)       3.006 (4.964)
-----------------------------------------------------------------------------------------------
Image_ID                                              -                   -                   x
-----------------------------------------------------------------------------------------------
R2                                                0.158               0.151               0.158
S.E. type                                        hetero              hetero              hetero
Observations                                       1440                1440                1440
-----------------------------------------------------------------------------------------------
Significance levels: * p < 0.05, ** p < 0.01, *** p < 0.001
Format of coefficient cell:
Coefficient (Std. Error)

<ipython-input-47-fe32e71d8aec>:10: FutureWarning: 'pyfixest.summarize.etable' is deprecated and will be removed in a future version.
Please use 'pyfixest.etable' instead. You may refer the updated documentation at: https://s3alfisc.github.io/pyfixest/quickstart.html
  etable([model_score, model_score_simple, model_score_fe])

In [ ]:
model_Mean_Score = feols(f"Mean_Score ~ Any_Treatment + Age + Gender + Attend_BU + Image_ID", data=df_cleaned_categorical_repeated).vcov("hetero")

model_Mean_Score_simple = feols(f"Mean_Score ~ Any_Treatment + Age + Gender + Image_ID", data=df_cleaned_categorical_repeated).vcov("hetero")

model_Mean_Score_fe = feols(f"Mean_Score ~ Any_Treatment + Age + Gender + Attend_BU | Image_ID", data=df_cleaned_categorical_repeated).vcov("hetero")

etable([model_Mean_Score, model_Mean_Score_simple, model_Mean_Score_fe])

                                                   est1                est2                est3
-----------------------------------  ------------------  ------------------  ------------------
depvar                                       Mean_Score          Mean_Score          Mean_Score
-----------------------------------------------------------------------------------------------
Intercept                             66.162*** (1.981)   64.099*** (1.931)
Any_Treatment                          -2.163** (0.820)     -1.775* (0.821)    -2.163** (0.813)
Age[T.25 - 34]                            1.155 (0.899)      2.063* (0.873)       1.155 (0.892)
Age[T.35 - 44]                          6.949** (2.475)     8.044** (2.546)     6.949** (2.456)
Age[T.45 - 54]                       -12.942*** (0.891)  -11.600*** (0.819)  -12.942*** (0.884)
Age[T.55 and older]                   10.233*** (1.033)   12.177*** (0.966)   10.233*** (1.025)
Age[T.Prefer not to say]              -3.375*** (0.992)   -5.531*** (0.924)   -3.375*** (0.985)
Age[T.Under 18]                           4.698 (3.162)      6.574* (3.127)       4.698 (3.137)
Gender[T.Male]                         3.636*** (0.816)    3.684*** (0.822)    3.636*** (0.809)
Gender[T.Non-binary / third gender]  -35.577*** (2.586)  -33.909*** (2.707)  -35.577*** (2.566)
Attend_BU                             -4.015*** (0.838)                       -4.015*** (0.832)
Image_ID[T.10]                            0.024 (2.486)      -0.336 (2.512)
Image_ID[T.11]                            0.945 (2.593)       0.459 (2.621)
Image_ID[T.12]                            1.234 (2.673)       0.756 (2.690)
Image_ID[T.13]                            1.313 (2.513)       0.894 (2.557)
Image_ID[T.14]                            0.001 (2.702)      -0.069 (2.703)
Image_ID[T.15]                            2.018 (2.856)       1.734 (2.863)
Image_ID[T.16]                            0.568 (2.584)       0.527 (2.571)
Image_ID[T.17]                           -0.003 (2.804)      -0.099 (2.833)
Image_ID[T.18]                           -2.838 (2.590)      -3.016 (2.598)
Image_ID[T.19]                            0.949 (2.532)       0.653 (2.538)
Image_ID[T.2]                            -1.690 (2.680)      -1.850 (2.686)
Image_ID[T.20]                            0.890 (2.513)       0.530 (2.520)
Image_ID[T.21]                            0.525 (2.513)       0.452 (2.518)
Image_ID[T.22]                           -1.659 (2.715)      -1.814 (2.710)
Image_ID[T.3]                             0.517 (2.715)       0.281 (2.736)
Image_ID[T.4]                             0.330 (2.824)       0.204 (2.819)
Image_ID[T.5]                             1.438 (2.613)       1.180 (2.618)
Image_ID[T.6]                            -0.242 (2.642)      -0.608 (2.642)
Image_ID[T.7]                             0.890 (2.607)       0.562 (2.634)
Image_ID[T.8]                            -0.257 (2.609)      -0.370 (2.631)
Image_ID[T.9]                             0.806 (2.618)       0.577 (2.661)
-----------------------------------------------------------------------------------------------
Image_ID                                              -                   -                   x
-----------------------------------------------------------------------------------------------
R2                                                0.136               0.123               0.136
S.E. type                                        hetero              hetero              hetero
Observations                                       1440                1440                1440
-----------------------------------------------------------------------------------------------
Significance levels: * p < 0.05, ** p < 0.01, *** p < 0.001
Format of coefficient cell:
Coefficient (Std. Error)

<ipython-input-48-66e7cf29411c>:7: FutureWarning: 'pyfixest.summarize.etable' is deprecated and will be removed in a future version.
Please use 'pyfixest.etable' instead. You may refer the updated documentation at: https://s3alfisc.github.io/pyfixest/quickstart.html
  etable([model_Mean_Score, model_Mean_Score_simple, model_Mean_Score_fe])

## Proportion Test

In [ ]:
from statsmodels.stats.proportion import proportions_ztest

z_stat, p_value = proportions_ztest(df_cleaned["Any_Treatment"].value_counts()[1], len(df_cleaned["Any_Treatment"]), 0.5)

# Print the Z-test statistic and p-value
print("Z-test statistic:", z_stat)
print("P-value:", p_value)

Z-test statistic: -0.3334620086260372
P-value: 0.7387855626520152

In [ ]:
df_cleaned_categorical_repeated["Image_ID"].value_counts()

21    75
20    72
19    71
14    70
22    70
13    69
10    68
16    67
17    67
2     66
6     66
8     65
12    64
1     64
3     64
11    63
15    63
9     63
18    60
4     59
5     57
7     57
Name: Image_ID, dtype: int64

In [ ]:
z_stat, p_value = proportions_ztest(df_cleaned_categorical_repeated["Image_ID"].value_counts()[0], len(df_cleaned_categorical_repeated["Image_ID"]), 1/df_cleaned_categorical_repeated["Image_ID"].nunique())

print("Z-test statistic:", z_stat)
print("P-value:", p_value)

Z-test statistic: 1.1320898654460456
P-value: 0.25759665519286223

In [ ]:
z_stat, p_value = proportions_ztest(df_cleaned_categorical_repeated["Image_ID"].value_counts()[-1], len(df_cleaned_categorical_repeated["Image_ID"]), 1/df_cleaned_categorical_repeated["Image_ID"].nunique())

print("Z-test statistic:", z_stat)
print("P-value:", p_value)

Z-test statistic: -1.1426756992799223
P-value: 0.25317326285880204

## Power Test

In [ ]:
!pip install pingouin

Collecting pingouin
  Downloading pingouin-0.5.4-py2.py3-none-any.whl (198 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.9/198.9 kB 5.1 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.11.4)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.5.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from pingouin) (3.7.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.13.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.14.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.2.2)
Collecting pandas-flavor (from pingouin)
  Downloading pandas_flavor-0.6.0-py3-none-any.whl (7.2 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->pingouin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->pingouin) (2023.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (3.1.1)
Requirement already satisfied: xarray in /usr/local/lib/python3.10/dist-packages (from pandas-flavor->pingouin) (2023.7.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pingouin) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pingouin) (3.3.0)
Requirement already satisfied: patsy>=0.5.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels->pingouin) (0.5.6)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.4->statsmodels->pingouin) (1.16.0)
Installing collected packages: pandas-flavor, pingouin
Successfully installed pandas-flavor-0.6.0 pingouin-0.5.4

In [ ]:
from statsmodels.stats.power import TTestPower

predicted_effect = -1
sd_outcome = 30

n = TTestPower().solve_power(effect_size=true_effect/sd_outcome, nobs=None, alpha=0.05, power=0.8, alternative='two-sided')

print(f"Necessary sample size: {np.ceil(n)}")

Necessary sample size: 787.0

In [ ]:
true_effect/sd_outcome

-0.1

In [ ]:
ATE = df_cleaned_categorical_repeated[df_cleaned_categorical_repeated["Any_Treatment"] == 1]["Score"].mean() - df_cleaned_categorical_repeated[df_cleaned_categorical_repeated["Any_Treatment"] == 0]["Score"].mean()
ATE

-1.4257528957528933

In [ ]:
STD = df_cleaned["Mean_Score"].std()

In [ ]:
effect_size = ATE / STD
sample_size = len(df_cleaned)

power_calculator = TTestPower()
power = power_calculator.solve_power(effect_size=effect_size,
                                     nobs=sample_size,
                                     alpha=0.05,
                                     power=None,
                                     alternative='two-sided')

print(f"Statistical Power: {np.ceil(power)}")

Statistical Power: 1.0

In [ ]:
effect_size

-0.08970053079066634

## Balanced Test

In [ ]:
df_cleaned.columns

Index(['StartDate', 'EndDate', 'Duration (in seconds)', 'Finished', 'Age',
       'Gender', 'Attend_BU', 'BU_School', '1', '2', '3', '4', '5', '6', '7',
       '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
       '20', '21', '22', 'Any_Treatment', 'Mean_Score', 'User_ID'],
      dtype='object')

In [ ]:
gender_mapping = {'Male': 0, 'Female': 1}
attend_mapping = {True: 1, False: 0}
age_mapping = {'Under 18': 0, '18 - 24': 1, '25 - 34': 2, '35 - 44': 3, '45 - 54': 4, '55 and older': 5, 'Prefer not to say': 6}

df_cleaned['Gender_Bool'] = df_cleaned['Gender'].map(gender_mapping)
df_cleaned['Attend_BU_Bool'] = df_cleaned['Attend_BU'].map(attend_mapping)
df_cleaned['Age_Bool'] = df_cleaned['Age'].map(age_mapping)

In [ ]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
from stargazer.stargazer import Stargazer

balance_test_Age = smf.ols("Age_Bool ~ Any_Treatment", data=df_cleaned).fit(cov_type='HC1')

balance_test_BU = smf.ols("Attend_BU_Bool ~ Any_Treatment", data=df_cleaned).fit(cov_type='HC1')

balance_test_Gender = smf.ols("Gender_Bool ~ Any_Treatment", data=df_cleaned).fit(cov_type='HC1')

Stargazer([balance_test_Age, balance_test_BU, balance_test_Gender])